import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
    <main className="min-h-screen w-full bg-pink-200">
        <div className="w-full max-w-7xl bg-pink-50 rounded-3xl p-6 md:p-10">
            <Toaster/>
            <div className="w-full h-18 bg-pink-100 p-4 rounded-4xl flex items-center justify-center ">
              <Header/>
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
